#!/usr/bin/env bash
# Customize login shell
# Add to .bashrc, .bash_profile or .profile by appending:
#   if [ -f ~/.bash_customize ]; then
#       . ~/.bash_customize
#   fi

# This file can change often. Easy reload.
alias .p='source ~/.bash_customize && echo "Reloading bash customizations..."'

# Set BASH_CUSTOMIZE_DIR (where the bash_customize is linked from)
PRG="$BASH_SOURCE"
progname=`basename "$BASH_SOURCE"`

while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`"/$link"
  fi
done

export BASH_CUSTOMIZE_DIR=$(dirname "$PRG")  

# Include functions
. "$BASH_CUSTOMIZE_DIR"/bash_functions




# All platforms ----------------------------------------------------------

set_platform

include_optional_scripts

set_custom_path

# Shortcuts
alias ?="h | g $1"
alias ..='cd ..'
alias ...='cd .. ; cd ..'
alias ducks='du -cksh * | sort -rn|head -11' 
      ## lists folders and files sizes in the current folder
alias f='find . -iname'
alias g="grep --color=auto"
alias h="history"
alias hexkey64="dd if=/dev/random bs=1 count=16 2>/dev/null |xxd -ps"
alias la='ls -a'
alias ll="ls -laF --color=auto"
alias m='more'
alias profileme="history | \
                 awk '{print \$2}' | \
                 awk 'BEGIN{FS=\"|\"}{print \$1}' | \
                 sort | uniq -c | sort -n | tail -n 20 | sort -nr"
      # from: http://lifehacker.com/software/how-to/turbocharge-your-terminal-274317.php
alias ps?="ps ax | g $1"
alias x="exit"

# History control
export HISTCONTROL=ignoreboth
export HISTFILESIZE=5000

# Use custom shell prompt
export PROMPT_COMMAND=bash_prompt_command

set_titlebar

unset set_titlebar

# Prompt with git branch
PS1="${W}<`uname -s` shell of doom:\h> [h:\! j:\j] ${EMY}\${NEW_PWD} ${EMR}\$(git_completion) \n ${EMW}\$ ${N}"



# Platform specific settings ---------------------------------------------

if [ "$PLATFORM" == "linux" ]; then
  
  # Define Linux specific configuration

  # Shortcut for text editor
  if [ -f `which komodo` ]; then
      alias m8='`which komodo` $1'
  fi


elif [ "$PLATFORM" == "darwin" ]; then
  
  # Define Mac specific configuration  

  textmate=`which mate`
  
  # Textmate for every editor
  if [ -f ${textmate} ]; then
      export EDITOR=${textmate}
  fi

  # Adding appropriate PATH & MANPATH variable for use with MacPorts.
  if [ -d /opt/local/etc/macports ]; then
      export PATH=/opt/local/bin:/opt/local/sbin:$PATH
      export MANPATH=/opt/local/share/man:$MANPATH
  fi

  # Textmate Shortcut (Must have mate command installed from Textmate 'About' Menu)
  if [ -f ${textmate} ]; then
      alias m8="${textmate} $1"
  fi

  
fi




